### ISSUE TITLE
How to save login credentials for auto-login?

### ISSUE THREAD

**Issue by thekenu** [KryDos/todoist-linux#102]
Each time I open the application, I have to manually sign in again. Is there a way to automate this process?

**Comment by KryDos** [comment]
hey @thekenu, 
There is no way to automate it (at least I don't know about such way) but the app should remember login credentials. I already forgot my password to Todoist since I'm always logged in. 

Could you please give me a bit more info about your operating system and about the way you installed the app.

**Comment by thekenu** [comment]
Hey @KryDos thanks for the quick response.

I am on Ubuntu 20.04 and I used the pre-built 1.23.0 deb package from https://github.com/KryDos/todoist-linux/releases. Would you recommend that I build from source or anything like that?

**Comment by KryDos** [comment]
@thekenu I don't think building it from source will help in any way unfortunately. 
As far as I know Electron (the base for this wrapper) store cookies and and cache data in `~/.config/Todoist` folder. Could you please take a look if that folder exists and if `Cookies` file is there?

**Comment by thekenu** [comment]
Yeah `~/.config/Todist/Cookies` and seemed to be populated be sane data. I actually just restarted my computer (It had been left on for days) and the auto-login seems to be working fine now! Closing the ticket ...
