### ISSUE TITLE
Several issues with global shortcut keys

### ISSUE THREAD

**Issue by nsheff** [KryDos/todoist-linux#106]
I just installed using `snap` on Ubuntu 19.10. I notice that, with Todoist runing:

- When I press Ctrl + Alt + A, nothing happens. I expected this to do a Quick Add, as suggested in the docs.
- When I press Ctrl + Alt + T, the todoist app opens. This is not listed in the docs as a keyboard short, so I didn't expect that -- and this is a problem because in gnome3, the Ctrl + Al t + T shortcut is typically used to open a **T**erminal, which is what I was expecting and use frequently.

I cannot figure out how to configure these due to a missing config file (posted in #104).

**Comment by nsheff** [comment]
My Gnome settings still say Ctrl+Alt+T should be Launch Terminal, but when Todoist is running, it switches focus to todoist instead.

![image](https://user-images.githubusercontent.com/5271009/92485721-4c536900-f1b9-11ea-9348-8c21b32b93c9.png)

**Comment by KryDos** [comment]
hi @nsheff, 

Did you install this app - https://snapcraft.io/todoist

Doist recently released their official Linux version and if you use that one please contact their support as described on their snap page either [here](https://get.todoist.help/) or [here](https://twitter.com/todoist).

This project is not official app. I think since their official linux app is release it's good time to update this project's readme file to make it more obvious that it is not an official app and point people to the official snap.
