### ISSUE TITLE
[Feature request] Start todoist on startup

### ISSUE THREAD

**Issue by tpondant** [KryDos/todoist-linux#108]
Hello,

Is there an option to automatically start todoist on startup? When I reboot, I don't see the todoist tray icon in my taskbar. I'm on Linux Mint 19 Cinnamon.

**Comment by KryDos** [comment]
hi @tpondant, 
Thanks for the suggestion. 

Even though it is a good idea I'd suggest to update your system to start Todoist at startup instead of doing something on the app side. 
I believe in Cinnamon you can go to Settings and find `Startup Applications` there. Just add Todoist app and it should work. 

Let me know if you were able to find that Startup Applications section. I didn't use Cinnamon for like ~3 years, maybe things have changed since then.

**Comment by tpondant** [comment]
Hi @KryDos, thank you for mentioning that. It can indeed be found in Startup Applications, hasn't changed for 3 years :) And I was able to find todoist in the apps.
