### ISSUE TITLE
Unable to logout of the application

### ISSUE THREAD

**Issue by c-shankar** [KryDos/todoist-linux#12]
As per your suggestion I installed the [latest release](https://github.com/KryDos/todoist-linux/releases/tag/1.8). I can log in to the account successfully but when I log out, it logs out at the time. But when I quit and reopen the app, the previous account is still logged in.

OS: Xubuntu 18.04 x64

**Comment by KryDos** [comment]
oh :( I'll take a look. Thanks

**Comment by cyfrost** [comment]
This issue is not observed (tested on Ubuntu 18.04) in [release 1.14](https://github.com/KryDos/todoist-linux/releases/tag/1.14). Looks safe to close this issue since its fixed @KryDos  :+1:

**Comment by KryDos** [comment]
hi @cyfrost, 
thanks a lot for checking that. 
Strangely, the bug is still exist for me (on Fedora).

Logout button works as expected but if I restart the app (not hide/show but real quit through menu or shortcut) then I'm getting back to my account. 

It seems like Todoist stores their auth data in Local Storage. I guess I could get instance of storage and just remove everything from there. Not sure why Logout button doesn't do it.

**Comment by cyfrost** [comment]
Oh, that's unfortunate. Let me see what I can do to fix it. I run Fedora as my main OS too.

**Comment by cyfrost** [comment]
Logout works as expected, tested on Fedora 29 workstation GNOME (Wayland) using [Todoist v1.15](https://github.com/KryDos/todoist-linux/releases/tag/1.15).

Installed todoist, logged in, logged back out, closed the app from tray, re-open todoist and was (pleasantly) greeted with this:

![image](https://user-images.githubusercontent.com/12471103/54471783-ea44be00-47e4-11e9-961f-1072bd5fe17b.png)

**Comment by KryDos** [comment]
hi @cyfrost,
thanks for checking this. I got similar message as on your screenshot too. It's not ideal but it actually logs user out so we're ok I guess. 

Thank again. 

@c-shankar let me know if you still experience this issue with the latest app version.
