### ISSUE TITLE
[Feature Request] Ability to set the zoom factor

### ISSUE THREAD

**Issue by c-shankar** [KryDos/todoist-linux#13]
I have a 1920x1080 monitor, and the text appear too small in the app. The global scaling is set to 130% but somehow this electron based app ignores the global scaling. The title bar and the tray menus show in correct size, but the actual todoist website itself is too small. Is there a way I could set and retain the zoom factor, using ctrl keys?

OS: Xubuntu 18.04 x64

**Comment by KryDos** [comment]
Hm... I'll try to find why it doesn't scale. Thanks.

**Comment by mickmattes** [comment]
I also have this same problem. The text is much too small. I just wanted to ask if there is any progress on this?
Greets

**Comment by KryDos** [comment]
hi @mickmattes 
I didn't look into this issue for long time. I'll try to look at it in few days. I'll let you know about the progress on it

**Comment by mickmattes** [comment]
Wow, that's a fast reply! Thank you KryDos. Really good job you do here...

**Comment by srntqn** [comment]
> I also have this same problem. The text is much too small. I just wanted to ask if there is any progress on this?
> Greets

@mickmattes as a temporary workaround you can change [force-device-scale-factor](https://github.com/KryDos/todoist-linux/blob/master/src/main.js#L141) value in the source code.

For example, 200% zoom:

`app.commandLine.appendSwitch('force-device-scale-factor', 2);`

After that build the app from source. For Ubuntu (or Debian) execute from project root:

`./node_modules/.bin/electron-builder --linux deb
`

**Comment by mickmattes** [comment]
> @mickmattes as a temporary workaround you can change [force-device-scale-factor](https://github.com/KryDos/todoist-linux/blob/master/src/main.js#L141) value in the source code.

@srntqn Great! This did the trick. With a factor of 2 it looks way too big though. But 1.5 looks great. Thanks for the hint. Maybe this should be part of the Readme, so everybody can set it to their own needs.

Thanks again!

**Comment by KryDos** [comment]
hi guys, 
that line to force device scale factor with value 1 was forcing the scale factor to 1 as you already found. 
Today I removed it completely and it seems like the app now respects the monitor scale factor. 

If you still need that option you can run the app with `--high-dpi-support=1 --force-device-scale-factor=1` options (replace `--force-device-scale-factor` value with the one you need). 

The app is NOT applying scale factor of a monitor "on the fly" unfortunately so you have to restart the app to see the changes. 

Let me know is this solution is working for you. If not, I'll reopen the ticket. 

[The Latest Version is HERE](https://github.com/KryDos/todoist-linux/releases/tag/1.14)

**Comment by mickmattes** [comment]
Where should I put these command line switches? I'm starting the app with `npm start` from the src folder.

**Comment by KryDos** [comment]
hi @mickmattes 

You cannot add those options to `npm start` command because `npm start` just executes a string defined in `package.json`. 

You have two options:

* Edit package.json (which is in `src` folder). 
  * Find `scripts` -> `start` section
  * Replace `electron .` with `electron . --high-dpi-support=1 --force-device-scale-factor=2` 

Another option is to use `./node_modules/.bin/electron . --high-dpi-support=1 --force-device-scale-factor=2` command instead of `npm start`

Could you please provide me with more info about this issue? The scaling should be automatic based on the scale factor of your monitor. As it described in my comment above the app cannot scale " on the fly" (when you move the app's window from one monitor to another) but it should work if you start the app from the monitor with bigger scale factor.

**Comment by mickmattes** [comment]
The issue is, that I'm using i3 window manager on a quite high resolution, because I need the screen space of my laptop. This forces applications that "auto-scale" to have small text. In most of the applications I use, I can scale them via CTRL-+ or so. If I use Todoist on this laptop, reading the tasks in Todoist is a real pita. Hopefully I could make my problem clear :-)
Thanks for you good work KryDos!

**Comment by AlexeyKot** [comment]
Maybe there is a way to make the app, so it respects "Ctrl +" shortcut to control zoom level as some other electron apps do like Spotify, VS Code, etc?

**Comment by stefan2904** [comment]
I also use i3 and have the mentioned problem. Starting it using the mentioned command (in my i3-autostart script) did the trick for me. Thanks!

`StartProg todoist --high-dpi-support=1 --force-device-scale-factor=1.5`
