### ISSUE TITLE
Problems with global Shortcuts

### ISSUE THREAD

**Issue by hellmrf** [KryDos/todoist-linux#134]
I've noticed that many system shortcuts are overridden when Todoist is running (in Ubuntu 20.04/GNOME 3.36.3). For instance, I can't use <kbd>Alt</kbd> + <kbd>↑</kbd> in my editor to move lines even if Todoist is minimized to tray. Maybe it's an electron bug, idk. I'm using the code in `master`.

If someone know what may be causing the problem, I can try to fix it and send a PR, but I really don't know.

**Comment by KryDos** [comment]
@hellmrf yeah, this issue is in this project since the beginning. 
I initially registered shortcuts as global and now we have this issue. 
[Even Alt+F4 closes todoist even if you try to close another app.](https://github.com/KryDos/todoist-linux/issues/65) 

It's interesting that Alt+↑ won't work, I thought Todoist don't have such shortcut. Do you have it in your .todoist-linux.json?
