### ISSUE TITLE
Can't log in with Google account

### ISSUE THREAD

**Issue by 12people** [KryDos/todoist-linux#15]
When choosing to log in with Google rather than a standard account, this dialog appears in my browser:

![google-login](https://user-images.githubusercontent.com/7361228/43370863-1793aeba-9387-11e8-877f-a0dc2cafdd0d.png)

I'm able to log in with Todoist username and password no problem. It's not a breaking bug, just a matter of comfort. (I had to look up my login credentials, because I didn't remember them.)

**Comment by KryDos** [comment]
@12people brilliant catch! Thanks a lot.

I'll let you know when it's fixed.

**Comment by jamzi** [comment]
Happens to me too, @KryDos do you have any ideas on this?

**Comment by jamzi** [comment]
Hey @KryDos. Spend some time today looking at this. I have a few questions:
- What should the correct oauth login flow look like, should you be redirected to your browser (outside electron context and back), but this produces csrf token errors.
- The second solution would be to do it via electron windows?

Yes, once you restart is all good, but the initial experience is not the best because it either crashes or becomes blank.

**Comment by KryDos** [comment]
hi @jamzi 
yeah, probably the second option is how I'm currently trying to implement it (without using a user's browser). 
Currently, I have a situation when oauth is working and user is logged in with no errors BUT the app closes (to tray) right after succesfull response from oAuth provider. It happens because I use the same Electron window for oAuth and when everything is ok then the window is closing. It is super non-obvious behavior. 

Maybe there is a way to use some kind of invisible tabs, so when the oAuth tab will be closed the "first"/"main" tab will be updated (how?). Or maybe I can show some kind of popup with oAuth provider in it... 

If you have any ideas on how to solve it, it would be so great. Let me know if I can help you with your research as well.

**Comment by KryDos** [comment]
hi guys, 
this issue has to be fixed in the latest [release 1.13](https://github.com/KryDos/todoist-linux/releases/tag/1.13)

@jamzi if you're interesting, the app detects if google's oauth link is going to be opened and creates a window with "on close" event attached. When oAuth-window is closed the main window is refreshing. There are some edge cases like if user close the oAuth window without login, but nothing really bad will happen in this case since the main window will reload to the same "login" page.
