### ISSUE TITLE
What license is this project under?

### ISSUE THREAD

**Issue by cyfrost** [KryDos/todoist-linux#32]
Hi,

Could you tell us what license your project is under? because I've not seen any mention in the repository itself. I run a fork of your project [here ](https://github.com/cyfrost/todoist-linux) and would like to know what licensing terms apply. If you specify no license at all, that means that I cannot modify your code ([except fork it on GitHub](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license)).

Since it is possible that a license was not added unintentionally, after reading the attached post [here](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license), would you still stay your project has no license? If yes, then I will have to retire my fork and delete it since I've made public changes to your code.

**Comment by KryDos** [comment]
hey @cyfrost ,
that's super hard question for me...

I don't really know what license I can choose since the app is a wrapper for the proprietary software (Todoist). Will my license (let's say MIT) conflict with Todoist? I don't know... I'll try to research this issue a bit and let you know. 

As for your fork, it looks great. I saw it already and I really like everything you did there. 
You don't need a license file in this project to continue maintain your fork. You just need to know that author of the original fork (me) is not going to perform any sanctions to you just because you modified the code. As far as I got the answer on Stackexchange, it suggests to assume worst scenario just to keep you protected in terms of any legal things. 

Please don't think I'm going to perform any legal-related actions to any fork this project has. It's not interesting.

**Comment by cyfrost** [comment]
Alright, Thanks!
