### ISSUE TITLE
Suggestion: add command string option to start minimized/in-tray

### ISSUE THREAD

**Issue by mikkovedru** [KryDos/todoist-linux#43]
Problem: I want to start Todoist-linux by default (from the startup applications), but that causes Todoist to be instantly visible. I don't want that and I am forced to always close/minimize the application. That's an extra hassle I would like to get rid of.

What I suggest is adding 2 command line options:
1. "-startintray". This puts Todoist automatically into tray.
2. "-minimized". This one automatically minimizes Todoist.

**Comment by gamkiller77** [comment]
Can we also add one for starting in full screen.  I made a Pi with the 7in screen and would be nice to have a like a kiosk mode. I got it to start at user load but i have to hit F11 would be nice if it would pop in to full screen mode.

**Comment by tukusejssirs** [comment]
While fullscreen/kiosk mode is a nice option, I’d like to see a _maximised_ option to open todoist maximised by default, or at least make to remember the last window size and place.

**Comment by KryDos** [comment]
hey @tukusejssirs, 
As far as I remember we use a package that should be able to remember the window size and position. Doesn't it work for you?

**Comment by Dude29** [comment]
@tukusejssirs Does the app being minimized differ from being only in the tray? Can you share screenshots if that is the case?
I ask because in my distro(Ubuntu 20.04) it is exactly the same.

**Comment by tukusejssirs** [comment]
@KryDos: I run your app directly from the cloned repo (using `/usr/local/bin/npm run --prefix "[repo_root]/src" start`), that might be the reason why it does not work if it works otherwise. It might be a good idea to create a config file in `~/.config/todoist` or a similar location, where would the wrapper config reside.

@Dude29: Generally speaking, when an app is _minimised_, it is minimised _to panel_ (like when you right-click a window title bar and select _Minimise_; on Ubuntu, it is minimised to the left panel AKA the dock), while _minimised to tray_ is simply hiding the window of an app, while accessible from a systray icon.

**Comment by Dude29** [comment]
Ah I see the distinction now. Ok, thanks for clarifying! :)
I use GNOME, yes.

**Comment by Dude29** [comment]
@KryDos Check out #95 I've made some changes there that will make implementing what @tukusejssirs, @gamkiller77 and @mikkovedru suggested a little easier

**Comment by tukusejssirs** [comment]
> As far as I remember we use a package that should be able to remember the window size and position. Doesn't it work for you?

@KryDos: another note on this: the app indeed remembers the window size and position, but not at startup / when the app is restarted. A setting might be added to the config file what state (maximised or custom windows size) should be used when the app is started (even when started minimised to systray, i.e. when no window is visible at first and only later on the app is opened). A better place for the state preservation would be some kind of cache, but a config is good enough for me (I seldom use non-maximised windows). :smiley:
