### ISSUE TITLE
CTRL+ALT+A doesn't work

### ISSUE THREAD

**Issue by ariya-mms** [KryDos/todoist-linux#51]
I installed .deb package in Kubuntu 18.04 LTS. All the shortcuts work except the most important one: Quickly adding a task!

**Comment by KryDos** [comment]
hi @ariya-mms,

I didn't test the app on KDE, but I believe the shortcut doesn't work because there is similar shortcut defined somewhere else (probably in KDE itself). 

Here is what I have found - https://docs.kde.org/trunk5/en/applications/fundamentals/kbd.html (search for `Activate Window Demanding Attention`). 

I can suggest two ways of solving it:

* Change KDE shortcuts (can't give you more details, I don't use KDE)
* Redefine the shortcut in the app's config (`~/.config/.todoist-linux.json`) and restart the app. 

Let me know if any of those helped.

**Comment by ariya-mms** [comment]
> hi @ariya-mms,
> 
> I didn't test the app on KDE, but I believe the shortcut doesn't work because there is similar shortcut defined somewhere else (probably in KDE itself).
> 
> Here is what I have found - https://docs.kde.org/trunk5/en/applications/fundamentals/kbd.html (search for `Activate Window Demanding Attention`).
> 
> I can suggest two ways of solving it:
> 
>     * Change KDE shortcuts (can't give you more details, I don't use KDE)
> 
>     * Redefine the shortcut in the app's config (`~/.config/.todoist-linux.json`) and restart the app.
> 
> 
> Let me know if any of those helped.

I changed the global KDE shortcut that had made this conflict and now it works, but after appearing the _quick add_ widget, I can't type in the field and instead my words appear in search field.

BTW, if KDE users want to use a shortcut for toggling full screen, they need to enable it in **System Settings > shortcuts > global shortcuts > KWin > Make Window Full Screen** and set its global value to **F11**.

**Comment by KryDos** [comment]
I'm happy that remapping shortcuts has helped. 

Thanks for reporting that new issue with wrong input focused. I've just created the issue for this here - https://github.com/KryDos/todoist-linux/issues/53

I hope that one can be solved easily. 

I'm closing this one.
