### ISSUE TITLE
Options for tray icon: Monochrome or hide from tray?

### ISSUE THREAD

**Issue by felix11h** [KryDos/todoist-linux#57]
Thank you for your work on the Linux version of this app! I was wondering if it would be possible to provide an option to have a monochrome tray icon or to hide the tray icon entirely. 

A first search indicates that it's not trivial to remove the icon from the user side (in my example Ubuntu 16.04) so I wonder if the app could provide this option. I'm not an expert in anything electron, but with some pointers I would be happy to also try and provide a pull request for this myself, maybe.

**Comment by KryDos** [comment]
hey @felix11h,
thanks a lot for good words! 

It seems like it's not easy to remove tray functionality because there are lot of functionality around it but I'm sure that monochrome icon is doable. 
Give me few days and I'll make the release with such icon and additional option in the config file to turn this icon on. 

If you can make the icon that fits your color scheme/preferences that would be great. You can find original icon file [here](https://raw.githubusercontent.com/KryDos/todoist-linux/master/build/icons/icon.png). I plan to use something like [this](https://imgur.com/jjMn2ug). Let me know if you think it's ok for your desktop.

**Comment by felix11h** [comment]
Thanks for the kind reply, @KryDos. A monochrome icon would be ideal, thank you for considering this. I did a quick [mock-up](https://imgur.com/a/dto9G3d) of what the monochrome icon could look like in the tray.

I'm just realizing that this might be pretty much your suggestion, as I know that imgur doesn't display transparency. I have the icon in white with transparency [here](https://github.com/felix11h/todoist-linux/blob/master/src/icons/monochrome_icon_transp.png), I'm not sure if it's helpful.

**Comment by KryDos** [comment]
hey @felix11h,

There is new version of the app available [here](https://github.com/KryDos/todoist-linux/releases/tag/1.18).
The main change is that monochrome like icon. By default the red icon is used but you can set `tray-icon` config property to `icon_monochrome.png`.

Here is my `~/.config/.todoist-linux.json` for reference:

```
{
    "quick-add": "CommandOrControl+Alt+a",
    "show-hide": "CommandOrControl+Alt+t",
    "refresh": "CommandOrControl+Alt+r",
    "tray-icon": "icon_monochrome.png"
}
```

And here is how does it look like 
![Screenshot_2019-12-08_15-08-42](https://user-images.githubusercontent.com/910691/70389172-d96c5600-19cc-11ea-8c51-93faf6bde2b7.png)

to get that red style icon back just use `icon.png` as value of the `tray-icon` property. I have update our readme file about this new property and possible values. 

Probably later I need to change the structure of that config file because right now keyboard shortcut related and style related properties are on the same level in the file and it looks a bit messy. 

Let me know please if everything is working on your side.

**Comment by felix11h** [comment]
This worked perfectly for me, thank you @KryDos! In Ubuntu 16.04 (Unity):

![ubuntu](https://user-images.githubusercontent.com/610633/70392418-40dfd100-19e0-11ea-9f8e-1fe43625a054.png)
