### ISSUE TITLE
AUR Package stuck in update loop

### ISSUE THREAD

**Issue by jrabensc** [KryDos/todoist-linux#80]
Hi, not quite sure if you maintain the AUR package as well. 

Currently, the update is stuck in a loop, see the comments here https://aur.archlinux.org/packages/todoist-electron/

Thanks.

**Comment by KryDos** [comment]
hi @jrabensc, other guys, with better knowledge of arch, helps me to maintain that package, but I'm the one who actually publish it. 
At the moment my arch VM is down after a massive update and I can't get into it and publish the changes made by @hausofwong. So the fix is here, in repo, but it's not published to AUR...

I actually didn't think that changes to AUR can be published from any machine (arch and arch-likes are not required). AUR is just a git repo.
I'll update this package in few days from another machine and let you know here. 

Thanks a lot for reminding me about this issue

**Comment by KryDos** [comment]
@jrabensc the update is pushed to AUR and I was able to install it from there. 

Let me know please if you still have any issues.
