### ISSUE TITLE
Cannot open todoist

### ISSUE THREAD

**Issue by ylqi007** [KryDos/todoist-linux#90]
When I tried to open or login todoist, it just showed a blank window and then just paused there.

![image](https://user-images.githubusercontent.com/23485976/85246220-abea7580-b40f-11ea-8b7a-43f195d191a1.png)

Can anyone help me, please?

**Comment by KryDos** [comment]
hi @ylqi007, 
could you please close the app and remove `~/.config/Todoist`.

**Comment by vitperov** [comment]
Hi KryDos!

I have the same issue, but with different picture:
![image](https://user-images.githubusercontent.com/3582851/97695893-cfa48300-1ab5-11eb-96fe-bc6781fe1a33.png)

`rm -rf ~/.config/Todoist/` doesn't change anything.

**Comment by KryDos** [comment]
hey @vitperov, 
thanks for letting me know about it. 

Looks interesting. That icon and loading gif must be centered. As far as I understand that loading process is never finished so probably some kind of JS error happened during the loading process. Does web version work fine on your side?

**Comment by vitperov** [comment]
Oh, sorry. It looks like new bug. I should have opened a new issue.

Yes, works fine in firefox. Just chcked in chomium - works.

**Comment by KryDos** [comment]
No worries, that's fine to keep this issue here. I'm currently not sure if your issue is the same as the one @ylqi007 experienced. 
I plan to update electron version during this weekend (PR is already waiting here - https://github.com/KryDos/todoist-linux/pull/128). I hope that will fix the issue. 

Is there any chance you can test the issue with one of the previous versions of the app? (all the releases are [here](https://github.com/KryDos/todoist-linux/releases)).
I wasn't able to reproduce it on my ubuntu. I'll try to reproduce it on clean ubuntu installation a bit later.

**Comment by vitperov** [comment]
Just tested version 1.18 - the same screen.

**Comment by rjhilgefort** [comment]
Looks like this is being worked on, but just wanted to chime in and say that I'm seeing this as well on Arch.

**Comment by kendoori** [comment]
I am also having the same issue with 1.24.0 on Linux Mint 20. Version 1.23.0 works.
